CREATE EXTENSION IF NOT EXISTS postgis;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE localities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  canton_code VARCHAR(2) NOT NULL,
  geom geometry(MultiPolygon, 4326) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT localities_name_canton_code_key UNIQUE (name, canton_code)
);

CREATE TABLE fan_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  locality_id BIGINT NOT NULL REFERENCES localities(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  pseudo VARCHAR(80) NOT NULL,
  anecdote TEXT,
  remark TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE locality_fan_counts (
  locality_id BIGINT PRIMARY KEY REFERENCES localities(id) ON DELETE CASCADE ON UPDATE CASCADE,
  fan_count INTEGER NOT NULL DEFAULT 0 CHECK (fan_count >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX localities_canton_code_idx ON localities (canton_code);
CREATE INDEX localities_name_idx ON localities (name);
CREATE INDEX localities_geom_gix ON localities USING GIST (geom);

CREATE INDEX fan_logs_locality_id_idx ON fan_logs (locality_id);
CREATE INDEX fan_logs_created_at_idx ON fan_logs (created_at DESC);
CREATE INDEX fan_logs_locality_id_created_at_idx ON fan_logs (locality_id, created_at DESC);

CREATE INDEX locality_fan_counts_fan_count_idx ON locality_fan_counts (fan_count DESC);
CREATE INDEX locality_fan_counts_updated_at_idx ON locality_fan_counts (updated_at DESC);

CREATE TRIGGER localities_set_updated_at
BEFORE UPDATE ON localities
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER locality_fan_counts_set_updated_at
BEFORE UPDATE ON locality_fan_counts
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();